name: $(major).$(minor).$(Rev:r)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - CloudFormation/Templates*

pool:
  vmImage: 'windows-latest'

variables:
  location: 'eastus-2'
  major: 1
  minor: 0

stages:
- stage: Publish
  displayName: Publish Templates to S3
  jobs:
  - job: Publish
    displayName: Publish Templates to S3
    steps:
      - task: S3Upload@1
        inputs:
          awsCredentials: 'aws-lws-d-azdevops-serviceconnection'
          regionName: $(location)
          bucketName: 'lws-eus2-d-cftemplates-s3'
          sourceFolder: ' $(Build.ArtifactStagingDirectory)/CloudFormation'
          globExpressions: '**'
          targetFolder: 'AWSCommunityBuilders/($build.buildnumber)'
          createBucket: true
