parameters:
  - name: 'awsServiceConnection'
    type: string
    default: false

steps:
  - checkout: self

  - task: CloudFormationCreateOrUpdateStack@1
    inputs:
      awsCredentials: ${{ parameters.awsServiceConnection }}
      regionName: $(region)
      stackName: 'LWSDeployments'
      templateSource: 'file'
      templateFile: '$(rootDir)/EKS/app-stack.yml'
      s3BucketName: 'lws-eus2-d-cftemplates-s3'
      templateParametersFile:  '$(rootDir)/EKS/parameters/parameters.$(environment).json'